spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: sarana-resturant-system
    datasource:
      url: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Phnom_Penh
    jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
          show-sql: true


server:
  port: 8081
springdoc:
  api-docs:
    enabled: true
Cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:}
  api_key: ${CLOUDINARY_API_KEY:}
  api_secret: ${CLOUDINARY_API_SECRET:}
